# Generated by Django 4.2.6 on 2023-10-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="username",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
