# Generated by Django 4.2.6 on 2023-10-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_login_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="password",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
