# Generated by Django 4.2.6 on 2023-10-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="olfa", max_length=50, verbose_name="title"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("content", models.TextField()),
                ("opinon", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="donner le path de image", upload_to="photos/%y/%m/%d"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[("phone", "phone"), ("computer", "computer")],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={"verbose_name": "name", "ordering": ["price"],},
        ),
    ]
