# Generated by Django 4.2.6 on 2023-10-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="donner le path de image", upload_to="photos"
            ),
        ),
    ]
